//
//  RecipeModel.swift
//  SultansKitchen_
//
//  Created by Ebru Zekir on 20.12.22.
//

import Foundation
enum Category: String, CaseIterable, Identifiable {
    var id: String {self.rawValue}
    case breakfast = "Breakfast"
    case soup = "Soup"
    case salad = "Salad"
    case appetizer = "Appetizer"
    case main = "Main"
    case side = "Side"
    case dessert = "Dessert"
    case snack = "Snack"
    case drink = "Drink"
}
struct Recipe: Identifiable{
    let id = UUID()
    let name: String
    let image: String
    let description: String
    let ingredients: String
    let directions: String
    let category: Category.RawValue
    let datePublished: String
    let url: String
    
}
extension Recipe
{
    static let all: [Recipe] = [
    Recipe(name: "Creamy mushroom soup",
           image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2Fs3NK5g-2Z6_heJcaCZFkHZOoqPg%3D%2F768x576%2Fimages.kitchenstories.io%2FrecipeImages%2F13_01_creamymushroomsoup_TitlePicture.jpg&w=1440&q=85",
           description: "When I think of comfort in a bowl, I think of this soup here",
           ingredients: "100 g dried mushrooms\n 600 ml water (hot)\n 2 shallots\n 1 clove garlic\n 200g button mushrooms\n 100 g porcini mushrooms\n 1½ tbsp butter\n 400 ml vegetable stock\n 3 egg yolks\n  200 ml heavy cream\n 20 g chives\n ½ tsp nutmeg (grated)\n 1 tbsp lemon juice\n 1 tsp sugar\n  salt",
           directions: "In a small, heat-resistant bowl, soak dried mushrooms in hot water for approx. 15 min. Finely chop shallots and garlic. Clean button and porcini mushrooms and cut into slices. Drain soaked mushrooms, make sure to keep the soaking liquid. In a saucepan, add two-thirds of the butter and sautée shallots and garlic until translucent. Add button mushrooms and dried mushrooms and continue sauteing for approx. 4 – 6min. Season with salt, pepper, and grated nutmeg.Pour in vegetable stock and most of the soaking liquid. Bring to a boil, turn down the heat, and let simmer for approx. 20 min. on low heat. Remove from heat and blend the soup with a hand blender. Whisk in heavy cream and egg yolks and season with lemon juice. Finely cut chives. In a frying pan, sauté porcini mushrooms in the remaining butter until cooked through. Add chives and season with salt and pepper. Transfer soup to a soup plate and add in porcini mushrooms. Serve with fresh bread. ",
           category: "Soup",
           datePublished: "2022-10-12",
           url:"https://www.kitchenstories.com/en/recipes/creamy-mushroom-soup"),
         Recipe(name: "Fluffy buttermilk pancakes",
                image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FfubEslr_d8Ngs84Q8biHMkkDTJQ%3D%2F768x576%2Fimages.kitchenstories.io%2FwagtailOriginalImages%2FR2726-photo-final-2.jpg&w=1440&q=85",
                description: "Best fluffy pancakes here",
                ingredients: "1 egg\n1 2 tbsp vegetable oil\n1 1½ tbsp maple syrup\n1  120 ml buttermilk\n1 100 g flour\n1  ½ tsp baking powder\n1  salt\n1 unsalted butter (for frying)\n1  jam (for serving)\n1 confectioner’s sugar (for serving)",
                directions: "Whisk egg in a mixing bowl until foamy. Add oil, maple syrup, and butter milk and continue whisking. Mix flour, baking powder, and a pinch of salt in a separate bowl and then gently fold into the liquid butter milk mixture. Let stand for approx. 15 – 20 min. Drop batter into skillet and cook on medium heat until golden-brown (approx. 2 – 3 min. per side, with a diameter of approx. 7cm). Serve with homemade jam or powdered sugar.",
                category: "Breakfast",
                datePublished: "2022-06-09",
                url: "https://www.kitchenstories.com/en/recipes/fluffy-buttermilk-pancakes"),
    Recipe(name: "SİMİT RECIPE 🤩",
           image: "https://cdn.yemek.com/mncrop/940/625/uploads/2017/11/citir-citir-ev-yapimi-sokak-simidi-tarifi.jpg", description: "Today, we are making the #1 street food of Turkey - crunchy sesame seed covered bagels that we call SİMİT 🤩We eat them in the morning as breakfast, with watermelon, during lunchtime, with cream cheese and even with hummus and falafel",
           ingredients: "For the dough\n1 1 kg strong flour (13% and higher protein works great, or bread flour would do great as well)\n1 1 heaped teaspoon instant yeast\n1 1 tablespoon salt\n1  600 ml lukewarm drinking water\n1  For the dip,\n1   1 cup of mulberry molasses (or grape molasses)\n1  1/2 cup of water\n1 1 tablespoon flour\n1 A generous amount of half-roasted sesame seeds\n1",
           directions: " Heat your oven to 280 C (535 F) on upper and lower heat with fan. If you have fire bricks (or oven stone) place them into the oven and heat them as well.To make the dough, it is quite important to choose a brand of flour with 13% protein content in order to achieve the classic simit taste. You can check the back of the flour package to see the protein level. If you can’t find, bread flour works great as well.Mix the instant yeast with the lukewarm drinking water and wait for a couple of minutes for yeast to wake up. Pile 1 kg of flour on the work surface (or in a bowl) and create a well at the center of the pile.Add the water to the well, then mix the flour and the water gradually. Knead for about 8-9 minutes until you reach a smooth, tackless consistency. If the dough is stiff, wet your fingers and keep on kneading.When your dough is ready, cover the bowl with a damp cloth and wait for half an hour. When it rises, knead once more and portion into 120 g lumps. By dividing each lump into two pieces you’ll get two 60 g lumps.First, shape the lumps into long strips (around 40-45 cm / 16-18 in). Then, take two strips side to side and wrap one another, forming a spiral.  Tie two ends of the spiral to form a circle and make sure you join them well.Dust your work surface and rest the simits while shaping others. Using a deep plate, pour the molasses, water and flour and mix well. On a separate tray pour a generous amount of sesame seeds. If you can’t find half-roasted sesame seeds you can roast them on a pan until they slightly change colour.Set your oven to 230 C (445 F) on upper and lower heat without fan.Starting with the first shaped one, dip your simits into the first station to coat with the molasses mixture, then to the second station to cover with sesame seeds.Then place them into the oven with a pizza peel and bake for 15-20 minutes until light brown and crunchy.",
           category:"Breakfast",
           datePublished: "2021-06-05",
           url: "https://www.youtube.com/watch?v=X96CR6ZPCg8"),
    Recipe(name: "Classic French toast",
           image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FGkxNQ6TYrK-zrx_p9DLqhsx2xVI%3D%2F768x576%2Fimages.kitchenstories.io%2FrecipeImages%2FFrenchToast_Final.jpg&w=1440&q=85",
           description: "Easy and quick",
           ingredients: "1 egg\n1 120 ml milk\n1 1 tbsp honey\n1 4 slices bread\n1 40 g unsalted butter\n1 1 pinch ground cinnamon\n1 maple syrup (for serving)",
           directions: "Whisk egg until foamy. Add milk, honey, and a pinch of cinnamon. Continue to beat until ingredients are well combined. Soak each side of bread in egg mixture. In a frying pan, melt butter over medium heat and sauté bread for approx. 2 – 3 min. per side until golden brown. Cut diagonally and serve with maple syrup.",
           category: "Breakfast",
           datePublished:" 2021-05-05",
           url: "https://www.kitchenstories.com/en/recipes/french-toast"),
    Recipe(name: "Shakshuka",
           image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FtEppUNX8iVAmLNEDDw-mwleBYJI%3D%2F864x648%2Fimages.kitchenstories.io%2FwagtailOriginalImages%2FR302-photo-title-sticker_1.jpg&w=1440&q=90", description: "Easy recipe for breakfast",
           ingredients: "1 onion\n1 1 clove garlic\n1 1 slice ginger\n1 1 chili\n1 1 red bell pepper\n1 1 yellow bell pepper\n1 1 tsp hot paprika powder\n1 1 tsp ground cumin\n1 800 g canned whole peeled tomatoes\n1 50 ml vegetable broth\n1 1 tbsp Worcestershire sauce\n1 4 eggs\n1 50 g feta cheese\n1  vegetable oil (for frying)\n1 parsley (for serving)",
           directions: "Finely dice onion, garlic, ginger, and chili. Cut bell peppers into thin strips. Dice tomatoes. Heat some vegetable oil in a frying pan over medium heat. Add onion, garlic, chili, and bell pepper, and sauté until soft, approx. 6 - 8 min. Then add ginger, spicy paprika, and cumin and cook for another 2 min. Add fresh tomatoes and canned tomatoes to the pan and lightly crush them with the cooking spoon. Preheat oven to 190°C/375°F. Add vegetable broth and cook over medium heat, stirring occasionally, for approx. 20 min. Stir in Worcestershire sauce and season with salt and pepper. Crack eggs into pan. Then crumble feta on top. Transfer to oven and bake at 190°C/375°F for approx. 7 - 10 min. until eggs have set. Remove from oven and garnish with fresh parsley to serve.",
           category:"Breakfast",
           datePublished: "2020-02-04",
           url: "https://www.kitchenstories.com/en/recipes/shakshuka"),
    Recipe(name: "Omelette with spinach and feta", image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FKtSYDR-j5wGfOoxtw8Ypiap2PDE%3D%2F864x648%2Fimages.kitchenstories.io%2FrecipeImages%2F16_13_spinachAndFetaOmelette_Final.jpg&w=1440&q=90", description: "Omelette with spinach and feta",
           ingredients: "5 eggs\n1 3 tbsp milk\n1 150 g spinach\n1 100 g feta\n1 freshly grated nutmeg\n1 salt\n1 pepper\n1 butter for frying",
           directions: "In a mixing bowl, whisk together eggs and milk. Season to taste with salt and pepper. In a frying pan, sauté the spinach until wilted. Season to taste with nutmeg, salt, and pepper. Set aside. Melt butter in frying pan, add eggs. Simmer on medium-low heat for approx. 1 min., then sprinkle spinach and feta on top. Fold omelette to close, like you would a letter, and continue to cook until heated through.Transfer to plate and enjoy!",
           category: "Breakfast",
           datePublished: "2020-10-03",
           url: "https://www.kitchenstories.com/en/recipes/omelette-with-spinach-and-feta"),
    Recipe(name: "Chocolate-strawberry naked cake"
           , image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FKZlc276hE3Yf7kD-BVOWCg8dbMI%3D%2F768x576%2Fimages.kitchenstories.io%2FrecipeImages%2FR713-photo-final-4x3.jpg&w=1440&q=85",
           description: "Naked cakes are cakes with exposed edges, where the different layers of cake remain clearly visible through thin layers of frosting. This chocolate naked cake with fresh strawberries is coated with a very thin layer of buttercream and finished with a decorative chocolate icing. It’s an eye-catcher for a wedding, birthday party, or really any other special event. Watch our video to see all the details of how to make this surprisingly simple, yet stunning cake.",
           ingredients: "2 eggs\n 120ml vegetable oil\n 240ml whole milk\n 240 ml water (hot)\n 250 g flour\n 65 g unsweetened cocoa powder\n 350g sugar\n 1 tsp salt\n 1½ tsp baking soda\n 1½ tsp baking powder\n 3 tsp vanilla sugar\n 225g butter\n 375g confectioner’s sugar\n 2 tbsp heavy cream\n 120g strawberries\n vegetable oil (for greasing)\n unsweetened cocoa powder (for dusting)\n chocolate glaze (for garnish)\n writing icing (for garnish)\n strawberry (for garnish)\n",
           directions: "Preheat oven to 180°C/350°F. Grease cake pans, line bottoms with parchment paper, and dust with cocoa powder, tapping the pans slightly to remove any excess. In a medium bowl, beat together eggs, oil, milk, and water. In a large bowl, combine flour, cocoa powder, sugar, salt, baking soda, baking powder, some of the vanilla sugar. Add wet ingredients to dry and mix until combined. Scrape batter into prepared pans. Bake cakes for about 20 – 25 min. at 180°C/350°F, or until a toothpick inserted into the center comes out clean or with a few moist crumbs. Allow to cool for 10 min. in the pan before unmolding, then let cake cool completely on a wire rack. Chill for approx. 15 – 30 min. so that cakes firm up. Meanwhile, make the buttercream: Beat butter until smooth. Gradually add powdered sugar and vanilla sugar and beat until light and fluffy. Add cream and continue to beat until smooth and creamy. If needed, add a bit more cream to loosen the buttercream until silky. Slice strawberries. If needed, cut off rounded cake tops with a serrated knife to make them level. Add one layer to cake plate and evenly spread some of the buttercream over it to cover. Top with a layer of strawberries, then add the second cake layer. Repeat, ending with adding the third layer of cake. Refrigerate for approx. 15 – 30 min. or until cake is cool and firmed up a bit. Thinly coat cake with remaining frosting, letting the chocolate cake peek through to achieve a “naked” look. Prepare chocolate glaze according to package instruction, then drip it over one of the edges of the cake. Garnish with strawberries and add writing, if you like. Enjoy!",
           category: "Dessert",
           datePublished: "2022-10-11",
           url: "https://www.kitchenstories.com/en/recipes/chocolate-strawberry-naked-cake"),
    Recipe(name: "Famous Turkish Baklava", image: "https://cdn.dsmcdn.com/ty140/product/media/images/20210705/17/107304444/143056367/2/2_org_zoom.jpg",
           description: "Baklava is the most famous Turkish dessert in the world. I am going to show you the easiest and most delicious way to make homemade baklava and it will be as if you’re eating it in Gaziantep, where you can find the best baklava in the world. With the crunchiness it is going to amaze you, sweetness will comfort you and finally pistachios will definitely pick you up and take you somewhere above the clouds!",
           ingredients: "For the syrup/şerbet\n  450 g sugar (2 cups + 2 tbsp)\n 340 ml water (1,5 cups)\n Lemon\n For the baklava\n 200 g butter\n 25 sheets of phyllo dough\n 200 g pistachio, roughly chopped\n Ice cream, optional for serving",
           directions: "Preheat the oven to 170 degrees (340F) on upper and lower heat without fan.  Combine the sugar and water in a saucepan and bring to boil over medium-high heat stirring until sugar dissolves. Make sure that the sugar melts completely before water starts to boil. Otherwise, sugar might be crystallized after syrup cools down.When it boils, lower the heat and simmer, uncovered, for about 10-11 minutes. The syrup is ready, add a few drops of lemon and set aside to cool at room temperature.To make the baklava, melt the butter on low heat in a saucepan without stirring to have clarified butter. After butter melted, remove from heat, and take out the foam that is formed on top of the butter. This is the milk part of the butter which will reduce the crunchiness of baklava and will get caramelized in the oven and leave small brown dots. Then slowly pour the clear butter in a small bowl and leave the milk part in the saucepan if there is any. Before starting it is better to sharpen your knife because you are going to need a sharp knife to cut the baklava.Place a phyllo sheet on your work surface and trim the phyllo according to your round tray’s bottom (around 30 cm/ 12 in). Cut the trimmed pieces into small pieces. Butter your tray and place three round shaped sheets and brush with the butter.After three round shaped layers place the scraps as three layers and butter again. Then continue with one round shaped sheet and 2 layers of scraps and butter.After using 10 of round shaped sheets, it is time for pistachio!Place the pistachios on top of the sheets and leave some space from the edges.Then continue layering the sheets with the same order. For the top part make sure that you are using more round shaped sheets to make baklava more beautiful (that is why we used more scraps than round ones for the bottom part).After all phyllo dough is finished tuck the layers with the back of a knife or a wooden knife. Using a sharp knife, cut the baklava into 12 slices like you are cutting pizza.After cutting, squeeze the slices from the sides with two fingers to give the perfect baklava shape. Brush all the remaining butter on top of the baklava, especially the edges and centre. Bake for about 25-30 minutes in total. First, place the baklava on the middle rack of your oven for 10 minutes. Then, transfer it to the bottom of the oven for 8 minutes. Finally, again the middle rack until it is golden.Take out from the oven and pour over the syrup. Let it cool down and soak all the syrup about one hour at room temperature.",
           category: "Dessert",
           datePublished: "2022-10-10",
           url: "https://www.youtube.com/watch?v=vrnH5UCMqLY"),
    Recipe(name: "Churros with chocolate sauce",
           image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2F9SEaVXPNgzVhWmfsg99JIG4dxH4%3D%2F768x576%2Fimages.kitchenstories.io%2FrecipeImages%2F24_10_CrunchyChrurrosWithChocolateSauce_TitlePicture.jpg&w=1440&q=85",
           description: "",
           ingredients: "250 ml water\n 100 g sugar\n 100 g butter\n ¼ tsp salt\n 200 g flour\n 4 eggs\n 50 ml cream\n 50 g sugar\n ½ vanilla bean (seeds)\n 100 g dark chocolate\n vegetable oil for frying\n cinnamon and sugar for garnish",
           directions: "In a large saucepan, bring water, sugar, butter and salt to a boil. Then add flour, reduce heat to medium, and cook while stirring constantly until dough is golden in color. Now, transfer dough to a stand mixer and allow to cool for approx. 5 – 10 min. Add eggs to stand mixer and beat until well incorporated and dough is smooth. Transfer dough to a star-tipped piping bag. Roughly chop chocolate. Add cream, sugar, and vanilla bean seeds to a small saucepan and cook over medium heat for approx. 3 – 5 min. Then add in chocolate and stir thoroughly until dissolved. Heat up some vegetable oil in a frying pan over medium-high heat and pipe strips of dough into pan and cook until both sides are golden brown. Then transfer to a paper towel-lined plate to dry. Garnish with cinnamon and sugar and serve with warm chocolate sauce.",
           category:"Dessert",
           datePublished: "",
           url: "https://www.kitchenstories.com/en/recipes/churros-with-chocolate-sauce"),
    Recipe(name: "Vanilla Butter Cake",
           image: "https://lh3.googleusercontent.com/UJx_wBBOsSAD7kM_KgSXhhyzcNFhzCio0WzC1wOtfXFbF6uGaoTR3l2fFMU2vNz8rizjZ68if2fMyy9J2u6o=w1280-h1280-c-rw-v1-e365", description: "Simply beautifully!",
           ingredients: "6 oz. unsalted butter (softened, plus 1 tablespoon for greasing pans)\n 2 cups sugar\n 4 eggs (room temperature)\n 2 1/2 cups all purpose flour (plus 1 tablespoon for greasing pans)\n 1/2 tsp. sea salt\n 2 tsp. baking powder\n 1 cup whole milk\n 2 tsp. vanilla",
           directions: "Preheat oven to 350°F. Generously grease two 9-inch round baking pans with 1 tablespoon butter, then sprinkle with 1 tablespoon flour, shaking out excess. Set aside.Attach flat beater to KitchenAid® Artisan® Stand Mixer. Add softened butter and sugar to mixer bowl, turn to speed 2, and mix 1 to 2 minutes. Gradually increase to speed 6 and beat until light and fluffy. Reduce to speed 4 and add eggs, one at a time until well incorporated.In separate bowl, combine flour, salt and baking powder. Add flour mixture to stand mixer bowl, mixing on speed 2 until just combined. Add half of milk and vanilla and mix to combine. Scrape down bowl and add remaining milk. Mix on speed 4, 1 to 2 minutes until completely blended.Divide batter evenly between prepared cake pans and bake 25-35 minutes until cakes spring back when pressed lightly and begin to pull away from sides of pans. Remove from oven and let cool on wire racks 15 minutes. Remove from pans and let cool completely.Finish cake with your favorite icing and serve",
           category: "Dessert", datePublished: "", url: "https://www.yummly.com/recipe/Vanilla-Butter-Cake-9082784"),
    Recipe(name: "Cream-filled doughnuts",
           image: "https://www.kitchenstories.com/_next/image?url=https%3A%2F%2Fimages.services.kitchenstories.io%2FzF55yXADS1WAyCe9n7e3TEXZMN4%3D%2F864x648%2Fimages.kitchenstories.io%2FwagtailOriginalImages%2FR2491-final-photo-_3.jpg&w=1440&q=90",
           description: "",
           ingredients: "530 ml milk\n 30 g fresh yeast\n 100 g sugar\n 2 eggs\n 2 egg yolks\n ½ tsp salt\n 500 g flour\n 100 g butter (room temperature)\n 1 vanilla bean\n 1 packagevanilla pudding powder\n 4 cl dark rum\n 200 g strawberry jam\n 200 g confectioner’s sugar\n vegetable oil (for deep frying)",
           directions: "Add milk, fresh yeast, sugar, eggs, egg yolks, and salt to the bowl of a kitchen machine with dough hook attachment. Whisk well to break up the yeast and eggs. Add flour and butter. Mix for approx. 10 min., or until the dough comes loose from the sides of the bowl and forms a ball. Transfer dough to a work surface to knead a bit longer with your hands, then form into a ball. The dough should spring back when gently pressed. Transfer back to the bowl, cover with a clean kitchen towel, and let rest for approx. 30 min. In the meantime, make the cream filling. Add most of the milk to a small saucepan. Add sugar to the saucepan Split and scrape vanilla bean and add seeds and scraped pod to saucepan. Heat over medium, whisking often. Add pudding powder to remaining milk in a separate bowl and whisk to combine. Once warmed through, add the pudding mixture to the saucepan and let cook, whisking constantly, approx. 2 – 3 min., or until thickened. Turn heat off, add rum, and whisk to combine. Transfer to a bowl (or piping bag), cover with plastic wrap, and chill while you finish the doughnuts. Transfer rested dough to a clean work surface. Divide dough into equal pieces approx. 60 g / 2 oz. Use your hands to form each into a smooth ball. Cover and let rest for approx. 30 min. Fill a wide pot with vegetable oil and set over medium heat. Once it reaches approx. 170°C/340°F (use a thermometer or a wooden spoon to test the oil temperature, if bubbles surround the handle of the wooden spoon right away, it’s ready). Carefully add the doughnuts to the pan one by one using a slotted spoon. Fry for approx. 2 min., then use a pair of tongs to flip. Fry for approx. 2 min. more, then transfer doughnuts to a paper towel-lined baking sheet. Repeat with all doughnuts. Let doughnuts cool for at least 5 min. Transfer chilled pudding to a piping bag with a long decorating tip and strawberry jam to another piping bag with a long decorating tip. Use the piping tip inserted into the side of each doughnut to fill with pudding or jam. Dust them all with confectioner’s sugar, then serve and enjoy!",
           category: "Dessert",
           datePublished: "2022-10-09",
           url: "https://www.kitchenstories.com/en/recipes/cream-filled-doughnuts"),
    Recipe(name: "Caesar Salad Roast Chicken",
           image: "https://assets.epicurious.com/photos/5f8e0436eb27e3e71e94dd98/1:1/w_2580%2Cc_limit/caesar-salad-roast-chicken-recipe-BA-101920.jpg",
           description: "The only thing better than a roast chicken and a Caesar salad is a Caesar salad served with a chicken smothered in Caesar dressing and roasted until the garlic, anchovies, and mustard become deeply caramelized and flavorful.",
           ingredients: "8 anchovies, mashed to a paste\n 8 garlic cloves, finely grated\n 6 Tbsp. mayonnaise, divided\n 1 Tbsp. Dijon mustard, plus more for serving\n 2 Tbsp. extra-virgin olive oil, divided\n 1½ tsp. freshly ground black pepper, plus more\n 1 (3½–4-lb.) whole chicken or 4 chicken legs (thigh and drumstick; about 3 lb.)\n Kosher salt\n 8 medium shallots, unpeeled, halved lengthwise\n 2 lemons, divided\n 1 oz. Parmesan, finely grated\n 4 oz. country-style bread, torn into (1½) pieces\n 2 romaine hearts, leaves separated, torn",
           directions: "Place a rack in lower third of oven; preheat to 450°F. Whisk anchovies, garlic, 3 Tbsp. mayonnaise, 1 Tbsp. mustard, 1 Tbsp. oil, and 1½ tsp. pepper in a small bowl. Set aside 1 Tbsp. anchovy mayo in another small bowl.Pat chicken dry; season outside and inside all over with salt. Arrange breast side up in a cast-iron skillet and tuck wings underneath. Arrange shallots around (if using legs, nestle under and around); season with salt and pepper. Brush remaining anchovy mayo all over chicken, making sure to get it into the nooks and crannies, then brush shallots with any leftover anchovy mayo. Place chicken in oven so legs are facing toward the back (this is the hottest part of the oven and will help the legs cook before the breast dries out) and roast until some anchovy mayo and fat begin to drip onto shallots, about 15 minutes. Remove from oven and, using tongs, turn shallots to coat in drippings. Return skillet to oven and continue to roast chicken, stirring shallots once or twice, until golden brown and an instant-read thermometer inserted into the thickest part of breast registers 155°F, 45–55 minutes. If skin starts to get too dark on the top before chicken is done, tent area with foil, leaving the rest of the bird exposed. If using chicken legs, start checking at 40 minutes (a thermometer inserted right at the joint should register 160°F). Transfer chicken and shallots to a cutting board, leaving behind any juices and fat in skillet. If shallots need more time to soften and darken, roast a bit longer without chicken before proceeding. Reserve skillet. Reduce oven temperature to 400°F. Finely grate half of zest of 1 lemon into a large bowl; cut lemon in half and squeeze in juice. Add reserved 1 Tbsp. anchovy mayo, remaining 3 Tbsp. mayo, and remaining 1 Tbsp. oil and whisk to combine, then stir in Parmesan. Season with salt and pepper. Set dressing aside.Add bread to reserved skillet with fat and turn to coat. Return skillet to oven and toast bread, tossing halfway through, until golden brown and crisp, 12–15 minutes. Transfer croutons to bowl with reserved dressing. Add romaine and gently toss until lettuce is well coated. Season salad with salt and pepper. Slice remaining lemon into wedges. Carve chicken and nestle back into skillet or transfer to a platter; arrange shallots and lemon wedges around. Serve with salad and more mustard alongside.",
           category: "Main", datePublished: "2022-10-08", url: "https://www.epicurious.com/recipes/food/views/caesar-salad-roast-chicken"),
    Recipe(name: "Molasses-Soy Glazed Salmon and Vegetables Recipe",
           image: "https://www.southernliving.com/thmb/Y6gP4Vsz3rhyZvJ2_9arM_LZ4SA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/2548301_QFSHe_646_0_0_0-fbd2a27e126942c8b33dbc3d696b0501.jpg",
           description: "In just 35 minutes, you can serve your family this incredibly delicious and good-for-you seafood supper. When it comes to busy weeknight dinners, quick and easy is the name of the game; and this tangy salmon with savory roasted vegetables is both full of flavor and hearty enough to satisfy the whole family. Make sure to cut the vegetables in similar sized pieces so they cook in the same amount of time. Couscous or quick cooking farro are both delicious and healthy substitutes for brown rice, and can be prepared while the rest of the meal is cooking. The tangy glaze is a great match for salmon, but it also pairs well with chicken and shrimp. Avoid buying thin fish fillets because they will finish cooking before the vegetables.",
           ingredients: "1/3 cup soy sauce\n 1/4 cup molasses\n 1 tablespoon freshly grated ginger\n 1 tablespoon rice vinegar\n 2 teaspoons minced garlic (about 2 garlic cloves)\n 1 bunch scallions (about 5 oz.)\n 6 ounces sugar snap peas (about 1 1/2 cups), trimmed\n 2 medium-size yellow bell peppers, cut into 1⁄2-inch-thick wedges\n 2 tablespoons olive oil\n 4 (6-oz.) skin-on salmon fillets\n 3/4 teaspoon kosher salt\n 1/2 teaspoon black pepper\n 2 (8.8-oz.) packages precooked microwavable brown rice\n 4 teaspoons toasted sesame seeds\n 4 lime wedges (optional)",
           directions: "Preheat oven to 400°F. Combine soy sauce, molasses, ginger, vinegar, and garlic in a small saucepan over medium. Cook, stirring often, until mixture simmers and reduces to about 1⁄2 cup, about 2 minutes. Remove from heat.Thinly slice green parts of scallions; reserve. Cut white parts of scallions into 1-inch pieces, and place on a large rimmed baking sheet. Add sugar snap peas and bell peppers. Drizzle vegetables with oil, and toss to coat. Spread in an even layer.Place salmon fillets, skin side down, nestled in vegetable mixture; spoon about 1 tablespoon molasses mixture over each fillet. Reserve remaining molasses mixture. Sprinkle salmon and vegetables evenly with salt and pepper. Place in preheated oven, and bake until vegetables are tender and lightly browned, salmon is cooked to medium, and glaze is golden, 16 to 18 minutes.Prepare rice according to package directions; divide evenly among serving plates. Place salmon and vegetables on plates; sprinkle with scallion slices and sesame seeds. Serve with remaining molasses mixture and, if desired, lime wedges.",
           category:"Main",
           datePublished: "2022-10-07",
           url: "https://www.southernliving.com/recipes/molasses-soy-glazed-salmon-and-vegetables-recipe")
    
    
    ]
    
}
